name: "🐛 Ho trovato un Bug"
description: Hai trovato un bug? Segnalalo!
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - riccardodebellini
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Dicci cosa è successo!
      description: Dicci anche quello che ti aspettavi succedesse!
      placeholder: Dì quello che vedi
      value: "è successo qualcosa"
    validations:
      required: true
  - type: input
    id: where
    attributes:
      label: Dove è successo?
      description: "Dicci dove è successo l'errore"
      placeholder: Home/Suggeriti...
      value: "Home/"
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      multiple: true
      label: Sistemi operativi
      description: "Su quale (o quali) sitema operativo trovi l'errore?"
      options:
        - Windows
        - Android
        - iOS
        - MacOS
        - Linux
      default: 0
    validations:
      required: true
  - type: dropdown
    id: edition
    attributes:
      label: Edizione
      description: "Su quale (o quali) edizioni trovi l'errore?"
      multiple: true
      options:
        - Web (riccardodebellini.github.io/mytomes)
        - App
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versione
      description: Che versione stai usando? (Rispondi solo se usi l'app, non la versione web)
      placeholder:  "1.0.0"
      value: "0.2"


